[general]
enabled = yes
bindaddr = 127.0.0.1
port = 5038
displayconnects = no

[asterisk-sandbox]
secret = ${ENV(AMI_SECRET)}
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,reporting
write = system,call,originate
