#!/usr/bin/env python3
"""Generate /etc/asterisk/pjsip.conf from endpoint specs + environment.

Run by scripts/render-configs.sh:
    python3 scripts/gen_pjsip.py | sudo tee /etc/asterisk/pjsip.conf

Stdlib only (no uv/venv needed, works under the render-configs invocation).
Reads SIP_PASS_* and DOMAIN from the environment. Adding an endpoint is one
line in ENDPOINTS below (+ the matching SIP_PASS_NN in .env).
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass


@dataclass(frozen=True)
class Endpoint:
    number: str
    kind: str  # "udp" (native softphones) | "webrtc" (browser)
    password_env: str


ENDPOINTS = [
    Endpoint("6001", "udp", "SIP_PASS_01"),
    Endpoint("6002", "udp", "SIP_PASS_02"),
    Endpoint("6003", "webrtc", "SIP_PASS_03"),
]

# Per-kind endpoint settings (everything after the shared header lines).
_KIND_SETTINGS = {
    "udp": [
        "allow=ulaw",
        "allow=alaw",
        "direct_media=no",
        "rtp_symmetric=yes",
        "force_rport=yes",
        "rewrite_contact=yes",
    ],
    "webrtc": [
        "allow=opus",
        "allow=ulaw",
        "webrtc=yes",
        "dtls_auto_generate_cert=yes",
        "rewrite_contact=yes",
    ],
}


def _transports(domain: str) -> list[str]:
    udp = [
        "[transport-udp]",
        "type=transport",
        "protocol=udp",
        "bind=0.0.0.0:5060",
    ]
    if domain:
        udp += [
            f"external_media_address={domain}",
            f"external_signaling_address={domain}",
        ]
    udp += ["local_net=172.31.0.0/16"]
    ws = [
        "; WebSocket transport for browser softphones (TLS terminated by nginx,",
        "; which proxies wss://.../ws -> ws://127.0.0.1:8088/ws). The bind is",
        "; required for the config to load; the actual WS socket is the http.conf",
        "; server on 8088 -- pjsip rides it rather than opening its own.",
        "[transport-ws]",
        "type=transport",
        "protocol=ws",
        "bind=0.0.0.0:8088",
    ]
    return udp + [""] + ws


def _endpoint(ep: Endpoint, password: str) -> list[str]:
    try:
        kind_settings = _KIND_SETTINGS[ep.kind]
    except KeyError:
        raise SystemExit(f"error: unknown kind {ep.kind!r} for endpoint {ep.number}") from None
    return [
        f"; Extension {ep.number} ({ep.kind})",
        f"[{ep.number}]",
        "type=endpoint",
        "context=internal",
        "disallow=all",
        f"auth=auth{ep.number}",
        f"aors={ep.number}",
        *kind_settings,
        "",
        f"[auth{ep.number}]",
        "type=auth",
        "auth_type=userpass",
        f"username={ep.number}",
        f"password={password}",
        "",
        f"[{ep.number}]",
        "type=aor",
        "max_contacts=2",
        "remove_existing=yes",
        "qualify_frequency=30",
    ]


def render(endpoints: list[Endpoint], env: dict[str, str]) -> str:
    lines = [
        "; GENERATED by scripts/gen_pjsip.py -- do not edit by hand.",
        "; Edit the ENDPOINTS list in that script, then re-run render-configs.sh.",
        "",
        *_transports(env.get("DOMAIN", "")),
    ]
    for ep in endpoints:
        password = env.get(ep.password_env, "")
        if not password:
            raise SystemExit(f"error: {ep.password_env} not set (endpoint {ep.number})")
        lines += ["", *_endpoint(ep, password)]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.stdout.write(render(ENDPOINTS, dict(os.environ)))
