#!/bin/bash
# Render the configs that carry secrets or deployment-specific values -- the
# AMI secret, SIP passwords, and $DOMAIN -- from .env, writing straight to /etc.
# Unlike the static configs (link-configs.sh), these can't be committed and
# symlinked without putting secrets and site-specifics in git. manager.conf and
# the nginx site are envsubst'd from *.template files; pjsip.conf is generated by
# gen_pjsip.py from endpoint specs. Run after editing .env, then restart services.
#
# The single-quoted '${VAR}' args to generate() below are envsubst's variable
# ALLOWLIST, not bash expansions -- they must stay literal so envsubst replaces
# only those vars and leaves real $-syntax in the configs intact (nginx $host,
# Asterisk dialplan ${EXTEN}). Double-quoting them would expand the secret in
# bash before envsubst runs, breaking the scoping and leaking it. SC2016 is
# therefore a false positive here and disabled file-wide.
# shellcheck disable=SC2016

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ ! -f "$REPO_ROOT/.env" ]]; then
    echo "error: .env not found -- copy .env.example and fill in values" >&2
    exit 1
fi

set -a
# shellcheck source=/dev/null
source "$REPO_ROOT/.env"
set +a

generate() {
    local vars="$1"
    local template="$2"
    local dest="$3"
    envsubst "$vars" < "$template" | sudo tee "$dest" > /dev/null
    echo "generated $dest"
}

generate '${AMI_SECRET}' \
    "$REPO_ROOT/asterisk/manager.conf.template" \
    /etc/asterisk/manager.conf

# pjsip.conf is generated from endpoint specs (not a static template) so adding
# an endpoint is one line in gen_pjsip.py. Stdlib python3; reads SIP_PASS_*/DOMAIN
# from the env sourced above. Capture first so a generator error (e.g. a missing
# SIP_PASS_NN) aborts via set -e WITHOUT truncating the live config; tee escalates.
pjsip_conf="$(python3 "$REPO_ROOT/scripts/gen_pjsip.py")"
# $(...) strips the generator's trailing newline; printf adds one back.
printf '%s\n' "$pjsip_conf" | sudo tee /etc/asterisk/pjsip.conf > /dev/null
echo "generated /etc/asterisk/pjsip.conf"

if [[ -n "${DOMAIN:-}" ]]; then
    generate '${DOMAIN}' \
        "$REPO_ROOT/nginx/pbx.conf.template" \
        "/etc/nginx/sites-available/$DOMAIN"
    echo "nginx config written -- symlink and reload nginx to apply"
fi

echo "done -- restart with: sudo systemctl restart asterisk && sudo systemctl reload nginx"
echo "note: asterisk-fastapi reconnects to AMI automatically after an asterisk restart (~1s)"
